<?php

namespace app\models;


use app\models\base\Word;
use yii\base\Exception;

class Session extends \app\models\base\Session {

    public function rules()
    {
        $rules = parent::rules();
        $rules[] = ['user_id', 'exist', 'targetClass' => User::className(), 'targetAttribute' => 'user_id'];

        return $rules;
    }

    public function fields() {
        return ['session_id', 'user_id', 'is_complete'];
    }

    public function beforeValidate()
    {
        $this->word_cnt = Word::find()->count();
        $this->passed_word_cnt = 0;

        return parent::beforeValidate(); // TODO: Change the autogenerated stub
    }

    public function beforeSave($insert) {

        if($this->isNewRecord) {
            $count = self::find()->where(['user_id' => $this->user_id, 'is_complete' => 0])->count();
            if($count > 0) {
                throw new Exception("Error create new Session, because previous session not complete");
            }

            $this->word_cnt = Word::find()->count();
        }

        return parent::beforeSave($insert);
    }

}