<?php

namespace app\models;

use yii\web\IdentityInterface;

class User extends \app\models\base\User  implements IdentityInterface {

    public function extraFields()
    {
        return ['activeSession'];
    }

    public function beforeValidate()
    {
        if(!$this->access_token) {
            $this->access_token = uniqid();
        }

        return parent::beforeValidate(); // TODO: Change the autogenerated stub
    }

    public static function findIdentityByAccessToken($token, $type = null)
    {
        return static::findOne(['access_token' => $token]);
    }


    public static function findIdentity($id)
    {
        return static::findOne($id);
    }

    public function getId()
    {
        return $this->user_id;
    }

    public function getAuthKey()
    {
        return $this->access_token;
    }

    public function validateAuthKey($authKey)
    {
        return $this->access_token == $authKey;
    }

    public function getActiveSession() {
        return $this->hasOne(Session::className(), ['user_id' => 'user_id'])->andWhere(['is_complete' => 0]);
    }
}